---
language: ruby
notifications:
  slack: bloomberg-rnd:BvYmxrV9xj902XWTRNrkLNkR
script: bundle exec rake travis
rvm:
  - 2.2
branches:
  only:
    - master
builder_args: --without kitchen_vagrant
matrix:
  fast_finish: true
